INSERT INTO instruktorzy (imie, nazwisko, telefon, mail, staz) VALUES('Mariusz', 'Krawiec', 218396744, 'MaKrawiec21@szkola.com', 4);
INSERT INTO instruktorzy (imie, nazwisko, telefon, mail, staz) VALUES('Jakub', 'Pietrzak', 597231025, 'JaPietrzak59@szkola.com', 3);
INSERT INTO instruktorzy (imie, nazwisko, telefon, mail, staz) VALUES('Adrianna', 'Żur', 792078421, 'AdŻur79@szkola.com', 0);
INSERT INTO instruktorzy (imie, nazwisko, telefon, mail, staz) VALUES('Dominika', 'Woźniak', 472840684, 'DoWoźniak47@szkola.com', 2);
INSERT INTO instruktorzy (imie, nazwisko, telefon, mail, staz) VALUES('Igor', 'Prus', 458507506, 'IgPrus45@szkola.com', 4);
INSERT INTO instruktorzy (imie, nazwisko, telefon, mail, staz) VALUES('Leon', 'Szewc', 593595537, 'LeSzewc59@szkola.com', 1);
INSERT INTO instruktorzy (imie, nazwisko, telefon, mail, staz) VALUES('Mateusz', 'Kozub', 777394600, 'MaKozub77@szkola.com', 3);
INSERT INTO instruktorzy (imie, nazwisko, telefon, mail, staz) VALUES('Karolina', 'Wieczorkiewicz', 359079700, 'KaWieczorkiewicz35@szkola.com', 5);
INSERT INTO instruktorzy (imie, nazwisko, telefon, mail, staz) VALUES('Katarzyna', 'Krawczyk', 183204337, 'KaKrawczyk18@szkola.com', 3);
INSERT INTO instruktorzy (imie, nazwisko, telefon, mail, staz) VALUES('Agnieszka', 'Mickiewicz', 196118523, 'AgMickiewicz19@szkola.com', 5);
INSERT INTO instruktorzy (imie, nazwisko, telefon, mail, staz) VALUES('Szymon', 'Myszka', 745409746, 'SzMyszka74@szkola.com', 5);
INSERT INTO instruktorzy (imie, nazwisko, telefon, mail, staz) VALUES('Piotr', 'Stoch', 548634678, 'PiStoch54@szkola.com', 1);
INSERT INTO instruktorzy (imie, nazwisko, telefon, mail, staz) VALUES('Tomasz', 'Mazur', 766919920, 'ToMazur76@szkola.com', 4);
INSERT INTO instruktorzy (imie, nazwisko, telefon, mail, staz) VALUES('Adrian', 'Krawczyk', 722732620, 'AdKrawczyk72@szkola.com', 5);
INSERT INTO instruktorzy (imie, nazwisko, telefon, mail, staz) VALUES('Szymon', 'Bizoń', 393513184, 'SzBizoń39@szkola.com', 4);
INSERT INTO instruktorzy (imie, nazwisko, telefon, mail, staz) VALUES('Antoni', 'Wieczorkiewicz', 467800466, 'AnWieczorkiewicz46@szkola.com', 0);
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Helena', 'Wójcik', 737812264, 'HeWójcik73@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Paweł', 'Żyła', 594058513, 'PaŻyła59@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Paweł', 'Królica', 927725698, 'PaKrólica92@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Piotr', 'Szewczenko', 336688676, 'PiSzewczenko33@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Zofia', 'Nowak', 219642406, 'ZoNowak21@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Jakub', 'Stasiak', 875730015, 'JaStasiak87@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Marianna', 'Serafin', 863216622, 'MaSerafin86@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Filip', 'Mickiewicz', 305929469, 'FiMickiewicz30@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Igor', 'Sowa', 288802604, 'IgSowa28@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Zuzanna', 'Sajewicz', 264935753, 'ZuSajewicz26@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Mariola', 'Sowa', 910257498, 'MaSowa91@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Zuzanna', 'Mickiewicz', 180427786, 'ZuMickiewicz18@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Agnieszka', 'Woźniak', 990005577, 'AgWoźniak99@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Katarzyna', 'Woźniak', 111252824, 'KaWoźniak11@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Zuzanna', 'Mazur', 300665248, 'ZuMazur30@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Hanna', 'Krawiec', 560462428, 'HaKrawiec56@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Dagmara', 'Stoch', 733095492, 'DaStoch73@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Marta', 'Sowa', 758095579, 'MaSowa75@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Zofia', 'Sosna', 580891370, 'ZoSosna58@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Marta', 'Mazur', 689430001, 'MaMazur68@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Antoni', 'Maj', 314764350, 'AnMaj31@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Aleksandra', 'Urbanek', 251337052, 'AlUrbanek25@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Adrian', 'Mickiewicz', 309943645, 'AdMickiewicz30@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Adrianna', 'Szewczenko', 329550659, 'AdSzewczenko32@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Bartosz', 'Marzec', 217698828, 'BaMarzec21@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Adrian', 'Krawczyk', 192078324, 'AdKrawczyk19@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Kamila', 'Marzec', 776964852, 'KaMarzec77@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Helena', 'Królica', 624145330, 'HeKrólica62@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Aleksander', 'Pietrzak', 134883170, 'AlPietrzak13@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Kamil', 'Wieczorkiewicz', 688884482, 'KaWieczorkiewicz68@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Zofia', 'Myszka', 338719841, 'ZoMyszka33@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Joanna', 'Sowa', 623633607, 'JoSowa62@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Kamila', 'Damek', 704883292, 'KaDamek70@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Stanisław', 'Sosna', 459537476, 'StSosna45@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Jakub', 'Kos', 590029810, 'JaKos59@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Zuzanna', 'Mickiewicz', 596575945, 'ZuMickiewicz59@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Leon', 'Nowak', 415386966, 'LeNowak41@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Aleksandra', 'Kozub', 927862106, 'AlKozub92@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Zofia', 'Plichta', 484160054, 'ZoPlichta48@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Szymon', 'Baran', 591708526, 'SzBaran59@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Marta', 'Kruk', 332057622, 'MaKruk33@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Stanisław', 'Śliwa', 772058145, 'StŚliwa77@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Mariusz', 'Maj', 893836546, 'MaMaj89@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Paulina', 'Zając', 210295453, 'PaZając21@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Helena', 'Student', 263631973, 'HeStudent26@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Marta', 'Serafin', 128523069, 'MaSerafin12@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Aleksander', 'Klimek', 908328742, 'AlKlimek90@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Dagmara', 'Nowak', 113021530, 'DaNowak11@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Szymon', 'Krawiec', 391546736, 'SzKrawiec39@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Zuzanna', 'Pietrzak', 909603291, 'ZuPietrzak90@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Aleksandra', 'Elsner', 761586730, 'AlElsner76@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Paulina', 'Kozub', 774305378, 'PaKozub77@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Mariola', 'Maj', 913477400, 'MaMaj91@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Dagmara', 'Brzoza', 896260040, 'DaBrzoza89@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Barbara', 'Damek', 421346140, 'BaDamek42@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Anna', 'Szewc', 222934727, 'AnSzewc22@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Beata', 'Mazur', 850019525, 'BeMazur85@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Aleksander', 'Mickiewicz', 770912423, 'AlMickiewicz77@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Mateusz', 'Foit', 685673195, 'MaFoit68@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Maja', 'Woźniak', 334783815, 'MaWoźniak33@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Karolina', 'Śliwa', 501697005, 'KaŚliwa50@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Antoni', 'Wieczorkiewicz', 858339372, 'AnWieczorkiewicz85@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Natalia', 'Żyła', 818331477, 'NaŻyła81@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Katarzyna', 'Kos', 516597483, 'KaKos51@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Leon', 'Szewc', 478766234, 'LeSzewc47@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Joanna', 'Kaczor', 975039158, 'JoKaczor97@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Adrianna', 'Kozub', 927338595, 'AdKozub92@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Marta', 'Elsner', 904349118, 'MaElsner90@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Marta', 'Kruk', 606307001, 'MaKruk60@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Karolina', 'Kruk', 853715095, 'KaKruk85@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Jarosław', 'Kozub', 634862400, 'JaKozub63@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Dominika', 'Maj', 194856841, 'DoMaj19@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Jarosław', 'Mickiewicz', 498890536, 'JaMickiewicz49@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Karolina', 'Szewczenko', 339624102, 'KaSzewczenko33@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Szymon', 'Zając', 277537308, 'SzZając27@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Dominika', 'Damek', 212649738, 'DoDamek21@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Kamila', 'Prus', 536850432, 'KaPrus53@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Karol', 'Kaczmarek', 155231879, 'KaKaczmarek15@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Leon', 'Woźniak', 740568756, 'LeWoźniak74@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Aleksandra', 'Student', 315350700, 'AlStudent31@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Adrianna', 'Krawiec', 806668660, 'AdKrawiec80@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Antonina', 'Ziętek', 156230225, 'AnZiętek15@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Jakub', 'Elsner', 191092495, 'JaElsner19@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Katarzyna', 'Sowa', 519988460, 'KaSowa51@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Mariusz', 'Szewc', 910383242, 'MaSzewc91@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Bartosz', 'Myszka', 892209790, 'BaMyszka89@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Stanisław', 'Szewc', 779517833, 'StSzewc77@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Antonina', 'Bizoń', 960575498, 'AnBizoń96@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Katarzyna', 'Żyła', 761323176, 'KaŻyła76@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Mariusz', 'Szewc', 262225919, 'MaSzewc26@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Antoni', 'Szewczenko', 262768045, 'AnSzewczenko26@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Stanisław', 'Mucha', 789482429, 'StMucha78@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Filip', 'Foit', 936800271, 'FiFoit93@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Zuzanna', 'Szewc', 507103529, 'ZuSzewc50@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Beata', 'Elsner', 559828306, 'BeElsner55@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Agnieszka', 'Krawczyk', 925954124, 'AgKrawczyk92@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Natalia', 'Nowak', 402153723, 'NaNowak40@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Antonina', 'Sowa', 582256449, 'AnSowa58@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Igor', 'Kaczor', 580798122, 'IgKaczor58@gmail.com');
INSERT INTO klienci (imie, nazwisko, telefon, mail) VALUES('Marta', 'Plichta', 305527481, 'MaPlichta30@gmail.com');


INSERT INTO taniec VALUES (1, 'Charlestone');
INSERT INTO taniec VALUES (2, 'Lindy Hop');
INSERT INTO taniec VALUES (3, 'Blues');
INSERT INTO taniec VALUES (4, 'Collegiate Shag');
INSERT INTO taniec VALUES (5, 'Balboa');



-- stworzenie tabeli wyplaty 
SELECT for_wyplaty_instruktorzy();

-- to nam doda do tabeli historia krotki z tabeli wyplaty (bo jest trigger)
DELETE FROM wyplaty WHERE True;

SELECT dodanie_uczestinka(72, 1, 1, 'leader', 'po', 11);
SELECT dodanie_uczestinka(40, 1, 1, 'leader', 'po', 11);
SELECT dodanie_uczestinka(79, 1, 1, 'leader', 'po', 11);
SELECT dodanie_uczestinka(58, 1, 1, 'follower', 'po', 11);
SELECT dodanie_uczestinka(93, 1, 1, 'leader', 'po', 11);
SELECT dodanie_uczestinka(82, 1, 1, 'leader', 'po', 11);
SELECT dodanie_uczestinka(49, 1, 1, 'leader', 'po', 11);
SELECT dodanie_uczestinka(72, 1, 1, 'follower', 'po', 11);
SELECT dodanie_uczestinka(1, 1, 1, 'leader', 'po', 11);
SELECT dodanie_uczestinka(11, 1, 1, 'follower', 'po', 11);
SELECT dodanie_uczestinka(94, 1, 1, 'leader', 'po', 11);
SELECT dodanie_uczestinka(65, 1, 1, 'follower', 'po', 11);
SELECT dodanie_uczestinka(100, 1, 1, 'leader', 'po', 11);
SELECT dodanie_uczestinka(70, 1, 1, 'leader', 'po', 11);
SELECT dodanie_uczestinka(75, 1, 1, 'follower', 'po', 11);
SELECT dodanie_uczestinka(2, 1, 1, 'follower', 'po', 11);
SELECT dodanie_uczestinka(100, 1, 1, 'follower', 'po', 11);
SELECT dodanie_uczestinka(5, 1, 1, 'follower', 'po', 11);
SELECT dodanie_uczestinka(69, 1, 1, 'follower', 'po', 11);
SELECT dodanie_uczestinka(69, 1, 1, 'leader', 'po', 11);
SELECT dodanie_uczestinka(1, 1, 1, 'leader', 'po', 11);
SELECT dodanie_uczestinka(89, 1, 1, 'follower', 'po', 11);
SELECT dodanie_uczestinka(79, 1, 1, 'leader', 'po', 11);
SELECT dodanie_uczestinka(98, 1, 1, 'follower', 'po', 11);
SELECT dodanie_uczestinka(31, 1, 1, 'follower', 'po', 11);
INSERT INTO prowadzacy VALUES (1, 1, 15, 7);

INSERT INTO zajecia VALUES(2,1,'po',13,0,0);
INSERT INTO zajecia VALUES(3,1,'po',15,0,0);
INSERT INTO zajecia VALUES(4,1,'po',17,0,0);
INSERT INTO zajecia VALUES(5,1,'po',19,0,0);
INSERT INTO zajecia VALUES(1,2,'wt',11,0,0);
INSERT INTO zajecia VALUES(2,2,'wt',13,0,0);
INSERT INTO zajecia VALUES(3,2,'wt',15,0,0);
INSERT INTO zajecia VALUES(4,2,'wt',17,0,0);
INSERT INTO zajecia VALUES(5,2,'wt',19,0,0);
INSERT INTO zajecia VALUES(1,3,'śr',11,0,0);
INSERT INTO zajecia VALUES(2,3,'śr',13,0,0);
INSERT INTO zajecia VALUES(3,3,'śr',15,0,0);
INSERT INTO zajecia VALUES(4,3,'śr',17,0,0);
INSERT INTO zajecia VALUES(5,3,'śr',19,0,0);
INSERT INTO zajecia VALUES(1,4,'czw',11,0,0);
INSERT INTO zajecia VALUES(2,4,'czw',13,0,0);
INSERT INTO zajecia VALUES(3,4,'czw',15,0,0);
INSERT INTO zajecia VALUES(4,4,'czw',17,0,0);
INSERT INTO zajecia VALUES(5,4,'czw',19,0,0);
INSERT INTO zajecia VALUES(1,5,'pt',11,0,0);
INSERT INTO zajecia VALUES(2,5,'pt',13,0,0);
INSERT INTO zajecia VALUES(3,5,'pt',15,0,0);
INSERT INTO zajecia VALUES(4,5,'pt',17,0,0);
INSERT INTO zajecia VALUES(5,5,'pt',19,0,0);


SELECT dodanie_uczestinka(68, 1, 2, 'follower', 'wt', 11);
SELECT dodanie_uczestinka(68, 1, 2, 'follower', 'wt', 11);
SELECT dodanie_uczestinka(78, 1, 2, 'leader', 'wt', 11);
SELECT dodanie_uczestinka(22, 1, 2, 'follower', 'wt', 11);
SELECT dodanie_uczestinka(30, 1, 2, 'follower', 'wt', 11);
SELECT dodanie_uczestinka(12, 1, 2, 'follower', 'wt', 11);
SELECT dodanie_uczestinka(22, 1, 2, 'leader', 'wt', 11);
SELECT dodanie_uczestinka(65, 1, 2, 'leader', 'wt', 11);
SELECT dodanie_uczestinka(2, 1, 2, 'follower', 'wt', 11);
SELECT dodanie_uczestinka(73, 1, 2, 'leader', 'wt', 11);
SELECT dodanie_uczestinka(58, 1, 2, 'leader', 'wt', 11);
SELECT dodanie_uczestinka(24, 1, 2, 'follower', 'wt', 11);
SELECT dodanie_uczestinka(84, 1, 2, 'leader', 'wt', 11);
SELECT dodanie_uczestinka(83, 1, 2, 'leader', 'wt', 11);
SELECT dodanie_uczestinka(87, 1, 2, 'follower', 'wt', 11);
SELECT dodanie_uczestinka(1, 1, 2, 'follower', 'wt', 11);
SELECT dodanie_uczestinka(93, 1, 2, 'leader', 'wt', 11);
SELECT dodanie_uczestinka(100, 1, 2, 'follower', 'wt', 11);
SELECT dodanie_uczestinka(35, 1, 2, 'leader', 'wt', 11);
SELECT dodanie_uczestinka(20, 1, 2, 'leader', 'wt', 11);
SELECT dodanie_uczestinka(31, 1, 2, 'follower', 'wt', 11);
SELECT dodanie_uczestinka(40, 1, 2, 'follower', 'wt', 11);
SELECT dodanie_uczestinka(13, 1, 2, 'leader', 'wt', 11);
SELECT dodanie_uczestinka(46, 1, 2, 'follower', 'wt', 11);
SELECT dodanie_uczestinka(52, 1, 2, 'follower', 'wt', 11);
INSERT INTO prowadzacy VALUES (1, 2, 4, 11);

SELECT dodanie_uczestinka(42, 1, 3, 'follower', 'śr', 11);
SELECT dodanie_uczestinka(84, 1, 3, 'follower', 'śr', 11);
SELECT dodanie_uczestinka(1, 1, 3, 'leader', 'śr', 11);
SELECT dodanie_uczestinka(20, 1, 3, 'follower', 'śr', 11);
SELECT dodanie_uczestinka(16, 1, 3, 'leader', 'śr', 11);
SELECT dodanie_uczestinka(100, 1, 3, 'follower', 'śr', 11);
SELECT dodanie_uczestinka(72, 1, 3, 'follower', 'śr', 11);
SELECT dodanie_uczestinka(50, 1, 3, 'follower', 'śr', 11);
SELECT dodanie_uczestinka(9, 1, 3, 'leader', 'śr', 11);
SELECT dodanie_uczestinka(98, 1, 3, 'follower', 'śr', 11);
SELECT dodanie_uczestinka(100, 1, 3, 'follower', 'śr', 11);
SELECT dodanie_uczestinka(100, 1, 3, 'follower', 'śr', 11);
SELECT dodanie_uczestinka(13, 1, 3, 'follower', 'śr', 11);
SELECT dodanie_uczestinka(92, 1, 3, 'leader', 'śr', 11);
SELECT dodanie_uczestinka(41, 1, 3, 'follower', 'śr', 11);
SELECT dodanie_uczestinka(20, 1, 3, 'leader', 'śr', 11);
SELECT dodanie_uczestinka(39, 1, 3, 'follower', 'śr', 11);
SELECT dodanie_uczestinka(94, 1, 3, 'leader', 'śr', 11);
SELECT dodanie_uczestinka(32, 1, 3, 'leader', 'śr', 11);
SELECT dodanie_uczestinka(45, 1, 3, 'follower', 'śr', 11);
SELECT dodanie_uczestinka(63, 1, 3, 'leader', 'śr', 11);
SELECT dodanie_uczestinka(59, 1, 3, 'leader', 'śr', 11);
SELECT dodanie_uczestinka(73, 1, 3, 'follower', 'śr', 11);
SELECT dodanie_uczestinka(34, 1, 3, 'leader', 'śr', 11);
SELECT dodanie_uczestinka(89, 1, 3, 'leader', 'śr', 11);
INSERT INTO prowadzacy VALUES (1, 3, 2, 4);

SELECT dodanie_uczestinka(31, 1, 4, 'leader', 'czw', 11);
SELECT dodanie_uczestinka(28, 1, 4, 'follower', 'czw', 11);
SELECT dodanie_uczestinka(63, 1, 4, 'leader', 'czw', 11);
SELECT dodanie_uczestinka(34, 1, 4, 'follower', 'czw', 11);
SELECT dodanie_uczestinka(38, 1, 4, 'follower', 'czw', 11);
SELECT dodanie_uczestinka(66, 1, 4, 'leader', 'czw', 11);
SELECT dodanie_uczestinka(82, 1, 4, 'follower', 'czw', 11);
SELECT dodanie_uczestinka(35, 1, 4, 'leader', 'czw', 11);
SELECT dodanie_uczestinka(66, 1, 4, 'follower', 'czw', 11);
SELECT dodanie_uczestinka(18, 1, 4, 'follower', 'czw', 11);
SELECT dodanie_uczestinka(78, 1, 4, 'follower', 'czw', 11);
SELECT dodanie_uczestinka(43, 1, 4, 'leader', 'czw', 11);
SELECT dodanie_uczestinka(44, 1, 4, 'leader', 'czw', 11);
SELECT dodanie_uczestinka(35, 1, 4, 'leader', 'czw', 11);
SELECT dodanie_uczestinka(72, 1, 4, 'follower', 'czw', 11);
SELECT dodanie_uczestinka(96, 1, 4, 'leader', 'czw', 11);
SELECT dodanie_uczestinka(15, 1, 4, 'leader', 'czw', 11);
SELECT dodanie_uczestinka(19, 1, 4, 'leader', 'czw', 11);
SELECT dodanie_uczestinka(97, 1, 4, 'leader', 'czw', 11);
SELECT dodanie_uczestinka(37, 1, 4, 'follower', 'czw', 11);
SELECT dodanie_uczestinka(3, 1, 4, 'follower', 'czw', 11);
SELECT dodanie_uczestinka(3, 1, 4, 'follower', 'czw', 11);
SELECT dodanie_uczestinka(33, 1, 4, 'leader', 'czw', 11);
SELECT dodanie_uczestinka(88, 1, 4, 'follower', 'czw', 11);
SELECT dodanie_uczestinka(10, 1, 4, 'leader', 'czw', 11);
INSERT INTO prowadzacy VALUES (1, 4, 16, 7);

SELECT dodanie_uczestinka(27, 1, 5, 'follower', 'pt', 11);
SELECT dodanie_uczestinka(58, 1, 5, 'follower', 'pt', 11);
SELECT dodanie_uczestinka(7, 1, 5, 'follower', 'pt', 11);
SELECT dodanie_uczestinka(30, 1, 5, 'leader', 'pt', 11);
SELECT dodanie_uczestinka(67, 1, 5, 'follower', 'pt', 11);
SELECT dodanie_uczestinka(100, 1, 5, 'leader', 'pt', 11);
SELECT dodanie_uczestinka(51, 1, 5, 'leader', 'pt', 11);
SELECT dodanie_uczestinka(53, 1, 5, 'leader', 'pt', 11);
SELECT dodanie_uczestinka(19, 1, 5, 'leader', 'pt', 11);
SELECT dodanie_uczestinka(96, 1, 5, 'follower', 'pt', 11);
SELECT dodanie_uczestinka(37, 1, 5, 'follower', 'pt', 11);
SELECT dodanie_uczestinka(17, 1, 5, 'leader', 'pt', 11);
SELECT dodanie_uczestinka(94, 1, 5, 'leader', 'pt', 11);
SELECT dodanie_uczestinka(54, 1, 5, 'leader', 'pt', 11);
SELECT dodanie_uczestinka(77, 1, 5, 'follower', 'pt', 11);
SELECT dodanie_uczestinka(60, 1, 5, 'leader', 'pt', 11);
SELECT dodanie_uczestinka(10, 1, 5, 'follower', 'pt', 11);
SELECT dodanie_uczestinka(8, 1, 5, 'leader', 'pt', 11);
SELECT dodanie_uczestinka(18, 1, 5, 'follower', 'pt', 11);
SELECT dodanie_uczestinka(42, 1, 5, 'leader', 'pt', 11);
SELECT dodanie_uczestinka(7, 1, 5, 'leader', 'pt', 11);
SELECT dodanie_uczestinka(39, 1, 5, 'follower', 'pt', 11);
SELECT dodanie_uczestinka(53, 1, 5, 'follower', 'pt', 11);
SELECT dodanie_uczestinka(75, 1, 5, 'follower', 'pt', 11);
SELECT dodanie_uczestinka(84, 1, 5, 'follower', 'pt', 11);
INSERT INTO prowadzacy VALUES (1, 5, 4, 14);

SELECT dodanie_uczestinka(42, 2, 5, 'follower', 'pt', 13);
SELECT dodanie_uczestinka(15, 2, 5, 'leader', 'pt', 13);
SELECT dodanie_uczestinka(88, 2, 5, 'follower', 'pt', 13);
SELECT dodanie_uczestinka(8, 2, 5, 'follower', 'pt', 13);
SELECT dodanie_uczestinka(27, 2, 5, 'leader', 'pt', 13);
SELECT dodanie_uczestinka(23, 2, 5, 'follower', 'pt', 13);
SELECT dodanie_uczestinka(44, 2, 5, 'follower', 'pt', 13);
SELECT dodanie_uczestinka(39, 2, 5, 'leader', 'pt', 13);
SELECT dodanie_uczestinka(40, 2, 5, 'follower', 'pt', 13);
SELECT dodanie_uczestinka(41, 2, 5, 'leader', 'pt', 13);
SELECT dodanie_uczestinka(13, 2, 5, 'leader', 'pt', 13);
SELECT dodanie_uczestinka(3, 2, 5, 'follower', 'pt', 13);
SELECT dodanie_uczestinka(85, 2, 5, 'follower', 'pt', 13);
SELECT dodanie_uczestinka(83, 2, 5, 'leader', 'pt', 13);
SELECT dodanie_uczestinka(30, 2, 5, 'leader', 'pt', 13);
SELECT dodanie_uczestinka(7, 2, 5, 'leader', 'pt', 13);
SELECT dodanie_uczestinka(82, 2, 5, 'leader', 'pt', 13);
SELECT dodanie_uczestinka(9, 2, 5, 'leader', 'pt', 13);
SELECT dodanie_uczestinka(23, 2, 5, 'follower', 'pt', 13);
SELECT dodanie_uczestinka(50, 2, 5, 'follower', 'pt', 13);
SELECT dodanie_uczestinka(60, 2, 5, 'leader', 'pt', 13);
SELECT dodanie_uczestinka(1, 2, 5, 'leader', 'pt', 13);
SELECT dodanie_uczestinka(3, 2, 5, 'leader', 'pt', 13);
SELECT dodanie_uczestinka(3, 2, 5, 'leader', 'pt', 13);
SELECT dodanie_uczestinka(48, 2, 5, 'leader', 'pt', 13);
INSERT INTO prowadzacy VALUES (2, 5, 14, 1);

SELECT dodanie_uczestinka(57, 2, 4, 'follower', 'czw', 13);
SELECT dodanie_uczestinka(73, 2, 4, 'follower', 'czw', 13);
SELECT dodanie_uczestinka(23, 2, 4, 'follower', 'czw', 13);
SELECT dodanie_uczestinka(24, 2, 4, 'follower', 'czw', 13);
SELECT dodanie_uczestinka(84, 2, 4, 'follower', 'czw', 13);
SELECT dodanie_uczestinka(91, 2, 4, 'follower', 'czw', 13);
SELECT dodanie_uczestinka(14, 2, 4, 'leader', 'czw', 13);
SELECT dodanie_uczestinka(68, 2, 4, 'follower', 'czw', 13);
SELECT dodanie_uczestinka(98, 2, 4, 'leader', 'czw', 13);
SELECT dodanie_uczestinka(81, 2, 4, 'follower', 'czw', 13);
SELECT dodanie_uczestinka(43, 2, 4, 'follower', 'czw', 13);
SELECT dodanie_uczestinka(39, 2, 4, 'leader', 'czw', 13);
SELECT dodanie_uczestinka(72, 2, 4, 'leader', 'czw', 13);
SELECT dodanie_uczestinka(10, 2, 4, 'leader', 'czw', 13);
SELECT dodanie_uczestinka(90, 2, 4, 'leader', 'czw', 13);
SELECT dodanie_uczestinka(69, 2, 4, 'follower', 'czw', 13);
SELECT dodanie_uczestinka(22, 2, 4, 'leader', 'czw', 13);
SELECT dodanie_uczestinka(85, 2, 4, 'leader', 'czw', 13);
SELECT dodanie_uczestinka(3, 2, 4, 'follower', 'czw', 13);
SELECT dodanie_uczestinka(97, 2, 4, 'follower', 'czw', 13);
SELECT dodanie_uczestinka(93, 2, 4, 'follower', 'czw', 13);
SELECT dodanie_uczestinka(36, 2, 4, 'leader', 'czw', 13);
SELECT dodanie_uczestinka(16, 2, 4, 'leader', 'czw', 13);
SELECT dodanie_uczestinka(40, 2, 4, 'leader', 'czw', 13);
SELECT dodanie_uczestinka(95, 2, 4, 'follower', 'czw', 13);
INSERT INTO prowadzacy VALUES (2, 4, 4, 3);

SELECT dodanie_uczestinka(7, 2, 3, 'leader', 'śr', 13);
SELECT dodanie_uczestinka(21, 2, 3, 'follower', 'śr', 13);
SELECT dodanie_uczestinka(37, 2, 3, 'follower', 'śr', 13);
SELECT dodanie_uczestinka(65, 2, 3, 'follower', 'śr', 13);
SELECT dodanie_uczestinka(56, 2, 3, 'leader', 'śr', 13);
SELECT dodanie_uczestinka(86, 2, 3, 'leader', 'śr', 13);
SELECT dodanie_uczestinka(90, 2, 3, 'follower', 'śr', 13);
SELECT dodanie_uczestinka(42, 2, 3, 'follower', 'śr', 13);
SELECT dodanie_uczestinka(99, 2, 3, 'follower', 'śr', 13);
SELECT dodanie_uczestinka(63, 2, 3, 'follower', 'śr', 13);
SELECT dodanie_uczestinka(32, 2, 3, 'follower', 'śr', 13);
SELECT dodanie_uczestinka(13, 2, 3, 'follower', 'śr', 13);
SELECT dodanie_uczestinka(37, 2, 3, 'follower', 'śr', 13);
SELECT dodanie_uczestinka(37, 2, 3, 'follower', 'śr', 13);
SELECT dodanie_uczestinka(46, 2, 3, 'leader', 'śr', 13);
SELECT dodanie_uczestinka(56, 2, 3, 'follower', 'śr', 13);
SELECT dodanie_uczestinka(47, 2, 3, 'leader', 'śr', 13);
SELECT dodanie_uczestinka(9, 2, 3, 'leader', 'śr', 13);
SELECT dodanie_uczestinka(99, 2, 3, 'leader', 'śr', 13);
SELECT dodanie_uczestinka(92, 2, 3, 'leader', 'śr', 13);
SELECT dodanie_uczestinka(28, 2, 3, 'leader', 'śr', 13);
SELECT dodanie_uczestinka(97, 2, 3, 'follower', 'śr', 13);
SELECT dodanie_uczestinka(5, 2, 3, 'follower', 'śr', 13);
SELECT dodanie_uczestinka(80, 2, 3, 'follower', 'śr', 13);
SELECT dodanie_uczestinka(52, 2, 3, 'leader', 'śr', 13);
INSERT INTO prowadzacy VALUES (2, 3, 6, 6);

SELECT dodanie_uczestinka(26, 2, 2, 'follower', 'wt', 13);
SELECT dodanie_uczestinka(97, 2, 2, 'follower', 'wt', 13);
SELECT dodanie_uczestinka(32, 2, 2, 'leader', 'wt', 13);
SELECT dodanie_uczestinka(89, 2, 2, 'follower', 'wt', 13);
SELECT dodanie_uczestinka(40, 2, 2, 'follower', 'wt', 13);
SELECT dodanie_uczestinka(32, 2, 2, 'leader', 'wt', 13);
SELECT dodanie_uczestinka(58, 2, 2, 'leader', 'wt', 13);
SELECT dodanie_uczestinka(96, 2, 2, 'leader', 'wt', 13);
SELECT dodanie_uczestinka(81, 2, 2, 'leader', 'wt', 13);
SELECT dodanie_uczestinka(38, 2, 2, 'leader', 'wt', 13);
SELECT dodanie_uczestinka(13, 2, 2, 'follower', 'wt', 13);
SELECT dodanie_uczestinka(89, 2, 2, 'leader', 'wt', 13);
SELECT dodanie_uczestinka(47, 2, 2, 'leader', 'wt', 13);
SELECT dodanie_uczestinka(87, 2, 2, 'follower', 'wt', 13);
SELECT dodanie_uczestinka(82, 2, 2, 'follower', 'wt', 13);
SELECT dodanie_uczestinka(4, 2, 2, 'leader', 'wt', 13);
SELECT dodanie_uczestinka(67, 2, 2, 'leader', 'wt', 13);
SELECT dodanie_uczestinka(92, 2, 2, 'leader', 'wt', 13);
SELECT dodanie_uczestinka(21, 2, 2, 'leader', 'wt', 13);
SELECT dodanie_uczestinka(52, 2, 2, 'leader', 'wt', 13);
SELECT dodanie_uczestinka(18, 2, 2, 'follower', 'wt', 13);
SELECT dodanie_uczestinka(98, 2, 2, 'leader', 'wt', 13);
SELECT dodanie_uczestinka(13, 2, 2, 'leader', 'wt', 13);
SELECT dodanie_uczestinka(21, 2, 2, 'follower', 'wt', 13);
SELECT dodanie_uczestinka(13, 2, 2, 'leader', 'wt', 13);
INSERT INTO prowadzacy VALUES (2, 2, 2, 14);

SELECT dodanie_uczestinka(89, 2, 1, 'follower', 'po', 13);
SELECT dodanie_uczestinka(32, 2, 1, 'follower', 'po', 13);
SELECT dodanie_uczestinka(72, 2, 1, 'leader', 'po', 13);
SELECT dodanie_uczestinka(12, 2, 1, 'leader', 'po', 13);
SELECT dodanie_uczestinka(33, 2, 1, 'follower', 'po', 13);
SELECT dodanie_uczestinka(62, 2, 1, 'follower', 'po', 13);
SELECT dodanie_uczestinka(26, 2, 1, 'leader', 'po', 13);
SELECT dodanie_uczestinka(24, 2, 1, 'leader', 'po', 13);
SELECT dodanie_uczestinka(72, 2, 1, 'leader', 'po', 13);
SELECT dodanie_uczestinka(5, 2, 1, 'follower', 'po', 13);
SELECT dodanie_uczestinka(29, 2, 1, 'leader', 'po', 13);
SELECT dodanie_uczestinka(43, 2, 1, 'follower', 'po', 13);
SELECT dodanie_uczestinka(57, 2, 1, 'leader', 'po', 13);
SELECT dodanie_uczestinka(78, 2, 1, 'leader', 'po', 13);
SELECT dodanie_uczestinka(90, 2, 1, 'follower', 'po', 13);
SELECT dodanie_uczestinka(68, 2, 1, 'leader', 'po', 13);
SELECT dodanie_uczestinka(28, 2, 1, 'follower', 'po', 13);
SELECT dodanie_uczestinka(82, 2, 1, 'follower', 'po', 13);
SELECT dodanie_uczestinka(40, 2, 1, 'follower', 'po', 13);
SELECT dodanie_uczestinka(49, 2, 1, 'follower', 'po', 13);
SELECT dodanie_uczestinka(77, 2, 1, 'leader', 'po', 13);
SELECT dodanie_uczestinka(10, 2, 1, 'leader', 'po', 13);
SELECT dodanie_uczestinka(54, 2, 1, 'follower', 'po', 13);
SELECT dodanie_uczestinka(83, 2, 1, 'follower', 'po', 13);
SELECT dodanie_uczestinka(51, 2, 1, 'follower', 'po', 13);
INSERT INTO prowadzacy VALUES (2, 1, 2, 16);

SELECT dodanie_uczestinka(13, 3, 1, 'follower', 'po', 15);
SELECT dodanie_uczestinka(37, 3, 1, 'leader', 'po', 15);
SELECT dodanie_uczestinka(22, 3, 1, 'leader', 'po', 15);
SELECT dodanie_uczestinka(93, 3, 1, 'follower', 'po', 15);
SELECT dodanie_uczestinka(3, 3, 1, 'leader', 'po', 15);
SELECT dodanie_uczestinka(14, 3, 1, 'leader', 'po', 15);
SELECT dodanie_uczestinka(48, 3, 1, 'follower', 'po', 15);
SELECT dodanie_uczestinka(24, 3, 1, 'leader', 'po', 15);
SELECT dodanie_uczestinka(29, 3, 1, 'follower', 'po', 15);
SELECT dodanie_uczestinka(4, 3, 1, 'follower', 'po', 15);
SELECT dodanie_uczestinka(9, 3, 1, 'leader', 'po', 15);
SELECT dodanie_uczestinka(47, 3, 1, 'follower', 'po', 15);
SELECT dodanie_uczestinka(96, 3, 1, 'follower', 'po', 15);
SELECT dodanie_uczestinka(61, 3, 1, 'leader', 'po', 15);
SELECT dodanie_uczestinka(64, 3, 1, 'follower', 'po', 15);
SELECT dodanie_uczestinka(69, 3, 1, 'follower', 'po', 15);
SELECT dodanie_uczestinka(83, 3, 1, 'follower', 'po', 15);
SELECT dodanie_uczestinka(95, 3, 1, 'follower', 'po', 15);
SELECT dodanie_uczestinka(90, 3, 1, 'leader', 'po', 15);
SELECT dodanie_uczestinka(9, 3, 1, 'leader', 'po', 15);
SELECT dodanie_uczestinka(42, 3, 1, 'follower', 'po', 15);
SELECT dodanie_uczestinka(40, 3, 1, 'follower', 'po', 15);
SELECT dodanie_uczestinka(5, 3, 1, 'leader', 'po', 15);
SELECT dodanie_uczestinka(39, 3, 1, 'leader', 'po', 15);
SELECT dodanie_uczestinka(70, 3, 1, 'leader', 'po', 15);
INSERT INTO prowadzacy VALUES (3, 1, 3, 13);

SELECT dodanie_uczestinka(100, 4, 1, 'leader', 'po', 17);
SELECT dodanie_uczestinka(68, 4, 1, 'leader', 'po', 17);
SELECT dodanie_uczestinka(93, 4, 1, 'follower', 'po', 17);
SELECT dodanie_uczestinka(98, 4, 1, 'follower', 'po', 17);
SELECT dodanie_uczestinka(9, 4, 1, 'leader', 'po', 17);
SELECT dodanie_uczestinka(70, 4, 1, 'follower', 'po', 17);
SELECT dodanie_uczestinka(23, 4, 1, 'leader', 'po', 17);
SELECT dodanie_uczestinka(82, 4, 1, 'follower', 'po', 17);
SELECT dodanie_uczestinka(14, 4, 1, 'follower', 'po', 17);
SELECT dodanie_uczestinka(10, 4, 1, 'leader', 'po', 17);
SELECT dodanie_uczestinka(52, 4, 1, 'follower', 'po', 17);
SELECT dodanie_uczestinka(40, 4, 1, 'leader', 'po', 17);
SELECT dodanie_uczestinka(49, 4, 1, 'leader', 'po', 17);
SELECT dodanie_uczestinka(81, 4, 1, 'follower', 'po', 17);
SELECT dodanie_uczestinka(23, 4, 1, 'follower', 'po', 17);
SELECT dodanie_uczestinka(39, 4, 1, 'follower', 'po', 17);
SELECT dodanie_uczestinka(9, 4, 1, 'leader', 'po', 17);
SELECT dodanie_uczestinka(28, 4, 1, 'follower', 'po', 17);
SELECT dodanie_uczestinka(97, 4, 1, 'leader', 'po', 17);
SELECT dodanie_uczestinka(95, 4, 1, 'leader', 'po', 17);
SELECT dodanie_uczestinka(73, 4, 1, 'leader', 'po', 17);
SELECT dodanie_uczestinka(63, 4, 1, 'follower', 'po', 17);
SELECT dodanie_uczestinka(55, 4, 1, 'follower', 'po', 17);
SELECT dodanie_uczestinka(33, 4, 1, 'leader', 'po', 17);
SELECT dodanie_uczestinka(33, 4, 1, 'leader', 'po', 17);
INSERT INTO prowadzacy VALUES (4, 1, 14, 10);

SELECT dodanie_uczestinka(47, 5, 1, 'leader', 'po', 19);
SELECT dodanie_uczestinka(43, 5, 1, 'leader', 'po', 19);
SELECT dodanie_uczestinka(31, 5, 1, 'leader', 'po', 19);
SELECT dodanie_uczestinka(90, 5, 1, 'follower', 'po', 19);
SELECT dodanie_uczestinka(43, 5, 1, 'leader', 'po', 19);
SELECT dodanie_uczestinka(10, 5, 1, 'follower', 'po', 19);
SELECT dodanie_uczestinka(11, 5, 1, 'follower', 'po', 19);
SELECT dodanie_uczestinka(4, 5, 1, 'follower', 'po', 19);
SELECT dodanie_uczestinka(75, 5, 1, 'leader', 'po', 19);
SELECT dodanie_uczestinka(18, 5, 1, 'leader', 'po', 19);
SELECT dodanie_uczestinka(16, 5, 1, 'follower', 'po', 19);
SELECT dodanie_uczestinka(38, 5, 1, 'leader', 'po', 19);
SELECT dodanie_uczestinka(52, 5, 1, 'leader', 'po', 19);
SELECT dodanie_uczestinka(22, 5, 1, 'follower', 'po', 19);
SELECT dodanie_uczestinka(9, 5, 1, 'leader', 'po', 19);
SELECT dodanie_uczestinka(42, 5, 1, 'follower', 'po', 19);
SELECT dodanie_uczestinka(92, 5, 1, 'follower', 'po', 19);
SELECT dodanie_uczestinka(70, 5, 1, 'leader', 'po', 19);
SELECT dodanie_uczestinka(5, 5, 1, 'follower', 'po', 19);
SELECT dodanie_uczestinka(40, 5, 1, 'follower', 'po', 19);
SELECT dodanie_uczestinka(12, 5, 1, 'leader', 'po', 19);
SELECT dodanie_uczestinka(95, 5, 1, 'follower', 'po', 19);
SELECT dodanie_uczestinka(18, 5, 1, 'leader', 'po', 19);
SELECT dodanie_uczestinka(29, 5, 1, 'leader', 'po', 19);
SELECT dodanie_uczestinka(13, 5, 1, 'follower', 'po', 19);
INSERT INTO prowadzacy VALUES (5, 1, 14, 9);

SELECT dodanie_uczestinka(74, 5, 2, 'follower', 'wt', 19);
SELECT dodanie_uczestinka(39, 5, 2, 'leader', 'wt', 19);
SELECT dodanie_uczestinka(9, 5, 2, 'leader', 'wt', 19);
SELECT dodanie_uczestinka(71, 5, 2, 'follower', 'wt', 19);
SELECT dodanie_uczestinka(8, 5, 2, 'leader', 'wt', 19);
SELECT dodanie_uczestinka(87, 5, 2, 'leader', 'wt', 19);
SELECT dodanie_uczestinka(30, 5, 2, 'leader', 'wt', 19);
SELECT dodanie_uczestinka(5, 5, 2, 'leader', 'wt', 19);
SELECT dodanie_uczestinka(40, 5, 2, 'follower', 'wt', 19);
SELECT dodanie_uczestinka(6, 5, 2, 'follower', 'wt', 19);
SELECT dodanie_uczestinka(81, 5, 2, 'leader', 'wt', 19);
SELECT dodanie_uczestinka(49, 5, 2, 'follower', 'wt', 19);
SELECT dodanie_uczestinka(67, 5, 2, 'leader', 'wt', 19);
SELECT dodanie_uczestinka(12, 5, 2, 'leader', 'wt', 19);
SELECT dodanie_uczestinka(92, 5, 2, 'follower', 'wt', 19);
SELECT dodanie_uczestinka(62, 5, 2, 'follower', 'wt', 19);
SELECT dodanie_uczestinka(79, 5, 2, 'follower', 'wt', 19);
SELECT dodanie_uczestinka(10, 5, 2, 'follower', 'wt', 19);
SELECT dodanie_uczestinka(92, 5, 2, 'follower', 'wt', 19);
SELECT dodanie_uczestinka(55, 5, 2, 'follower', 'wt', 19);
SELECT dodanie_uczestinka(78, 5, 2, 'leader', 'wt', 19);
SELECT dodanie_uczestinka(75, 5, 2, 'follower', 'wt', 19);
SELECT dodanie_uczestinka(64, 5, 2, 'leader', 'wt', 19);
SELECT dodanie_uczestinka(92, 5, 2, 'follower', 'wt', 19);
SELECT dodanie_uczestinka(53, 5, 2, 'leader', 'wt', 19);
INSERT INTO prowadzacy VALUES (5, 2, 1, 3);

SELECT dodanie_uczestinka(55, 4, 2, 'leader', 'wt', 17);
SELECT dodanie_uczestinka(100, 4, 2, 'leader', 'wt', 17);
SELECT dodanie_uczestinka(73, 4, 2, 'follower', 'wt', 17);
SELECT dodanie_uczestinka(63, 4, 2, 'leader', 'wt', 17);
SELECT dodanie_uczestinka(89, 4, 2, 'follower', 'wt', 17);
SELECT dodanie_uczestinka(44, 4, 2, 'follower', 'wt', 17);
SELECT dodanie_uczestinka(43, 4, 2, 'follower', 'wt', 17);
SELECT dodanie_uczestinka(7, 4, 2, 'leader', 'wt', 17);
SELECT dodanie_uczestinka(24, 4, 2, 'follower', 'wt', 17);
SELECT dodanie_uczestinka(37, 4, 2, 'leader', 'wt', 17);
SELECT dodanie_uczestinka(14, 4, 2, 'leader', 'wt', 17);
SELECT dodanie_uczestinka(92, 4, 2, 'follower', 'wt', 17);
SELECT dodanie_uczestinka(30, 4, 2, 'follower', 'wt', 17);
SELECT dodanie_uczestinka(8, 4, 2, 'follower', 'wt', 17);
SELECT dodanie_uczestinka(28, 4, 2, 'follower', 'wt', 17);
SELECT dodanie_uczestinka(58, 4, 2, 'leader', 'wt', 17);
SELECT dodanie_uczestinka(28, 4, 2, 'follower', 'wt', 17);
SELECT dodanie_uczestinka(62, 4, 2, 'follower', 'wt', 17);
SELECT dodanie_uczestinka(54, 4, 2, 'leader', 'wt', 17);
SELECT dodanie_uczestinka(85, 4, 2, 'leader', 'wt', 17);
SELECT dodanie_uczestinka(21, 4, 2, 'follower', 'wt', 17);
SELECT dodanie_uczestinka(77, 4, 2, 'follower', 'wt', 17);
SELECT dodanie_uczestinka(42, 4, 2, 'follower', 'wt', 17);
SELECT dodanie_uczestinka(12, 4, 2, 'follower', 'wt', 17);
SELECT dodanie_uczestinka(50, 4, 2, 'follower', 'wt', 17);
INSERT INTO prowadzacy VALUES (4, 2, 5, 6);

SELECT dodanie_uczestinka(89, 3, 2, 'leader', 'wt', 15);
SELECT dodanie_uczestinka(43, 3, 2, 'leader', 'wt', 15);
SELECT dodanie_uczestinka(87, 3, 2, 'leader', 'wt', 15);
SELECT dodanie_uczestinka(31, 3, 2, 'leader', 'wt', 15);
SELECT dodanie_uczestinka(9, 3, 2, 'follower', 'wt', 15);
SELECT dodanie_uczestinka(21, 3, 2, 'leader', 'wt', 15);
SELECT dodanie_uczestinka(55, 3, 2, 'follower', 'wt', 15);
SELECT dodanie_uczestinka(61, 3, 2, 'follower', 'wt', 15);
SELECT dodanie_uczestinka(9, 3, 2, 'follower', 'wt', 15);
SELECT dodanie_uczestinka(40, 3, 2, 'leader', 'wt', 15);
SELECT dodanie_uczestinka(56, 3, 2, 'leader', 'wt', 15);
SELECT dodanie_uczestinka(37, 3, 2, 'leader', 'wt', 15);
SELECT dodanie_uczestinka(31, 3, 2, 'leader', 'wt', 15);
SELECT dodanie_uczestinka(40, 3, 2, 'leader', 'wt', 15);
SELECT dodanie_uczestinka(52, 3, 2, 'leader', 'wt', 15);
SELECT dodanie_uczestinka(54, 3, 2, 'leader', 'wt', 15);
SELECT dodanie_uczestinka(19, 3, 2, 'leader', 'wt', 15);
SELECT dodanie_uczestinka(97, 3, 2, 'leader', 'wt', 15);
SELECT dodanie_uczestinka(52, 3, 2, 'follower', 'wt', 15);
SELECT dodanie_uczestinka(10, 3, 2, 'leader', 'wt', 15);
SELECT dodanie_uczestinka(7, 3, 2, 'follower', 'wt', 15);
SELECT dodanie_uczestinka(90, 3, 2, 'leader', 'wt', 15);
SELECT dodanie_uczestinka(95, 3, 2, 'follower', 'wt', 15);
SELECT dodanie_uczestinka(14, 3, 2, 'leader', 'wt', 15);
SELECT dodanie_uczestinka(40, 3, 2, 'leader', 'wt', 15);
INSERT INTO prowadzacy VALUES (3, 2, 11, 13);

SELECT dodanie_uczestinka(43, 3, 3, 'leader', 'śr', 15);
SELECT dodanie_uczestinka(53, 3, 3, 'leader', 'śr', 15);
SELECT dodanie_uczestinka(65, 3, 3, 'leader', 'śr', 15);
SELECT dodanie_uczestinka(7, 3, 3, 'follower', 'śr', 15);
SELECT dodanie_uczestinka(96, 3, 3, 'leader', 'śr', 15);
SELECT dodanie_uczestinka(14, 3, 3, 'leader', 'śr', 15);
SELECT dodanie_uczestinka(88, 3, 3, 'leader', 'śr', 15);
SELECT dodanie_uczestinka(91, 3, 3, 'leader', 'śr', 15);
SELECT dodanie_uczestinka(54, 3, 3, 'follower', 'śr', 15);
SELECT dodanie_uczestinka(69, 3, 3, 'leader', 'śr', 15);
SELECT dodanie_uczestinka(45, 3, 3, 'follower', 'śr', 15);
SELECT dodanie_uczestinka(22, 3, 3, 'leader', 'śr', 15);
SELECT dodanie_uczestinka(65, 3, 3, 'leader', 'śr', 15);
SELECT dodanie_uczestinka(51, 3, 3, 'leader', 'śr', 15);
SELECT dodanie_uczestinka(2, 3, 3, 'follower', 'śr', 15);
SELECT dodanie_uczestinka(20, 3, 3, 'leader', 'śr', 15);
SELECT dodanie_uczestinka(84, 3, 3, 'leader', 'śr', 15);
SELECT dodanie_uczestinka(95, 3, 3, 'leader', 'śr', 15);
SELECT dodanie_uczestinka(32, 3, 3, 'leader', 'śr', 15);
SELECT dodanie_uczestinka(6, 3, 3, 'leader', 'śr', 15);
SELECT dodanie_uczestinka(15, 3, 3, 'follower', 'śr', 15);
SELECT dodanie_uczestinka(56, 3, 3, 'follower', 'śr', 15);
SELECT dodanie_uczestinka(99, 3, 3, 'leader', 'śr', 15);
SELECT dodanie_uczestinka(58, 3, 3, 'leader', 'śr', 15);
SELECT dodanie_uczestinka(41, 3, 3, 'follower', 'śr', 15);
INSERT INTO prowadzacy VALUES (3, 3, 8, 13);

SELECT dodanie_uczestinka(65, 4, 3, 'follower', 'śr', 17);
SELECT dodanie_uczestinka(46, 4, 3, 'leader', 'śr', 17);
SELECT dodanie_uczestinka(42, 4, 3, 'follower', 'śr', 17);
SELECT dodanie_uczestinka(44, 4, 3, 'leader', 'śr', 17);
SELECT dodanie_uczestinka(62, 4, 3, 'leader', 'śr', 17);
SELECT dodanie_uczestinka(19, 4, 3, 'leader', 'śr', 17);
SELECT dodanie_uczestinka(22, 4, 3, 'follower', 'śr', 17);
SELECT dodanie_uczestinka(48, 4, 3, 'follower', 'śr', 17);
SELECT dodanie_uczestinka(25, 4, 3, 'leader', 'śr', 17);
SELECT dodanie_uczestinka(26, 4, 3, 'leader', 'śr', 17);
SELECT dodanie_uczestinka(95, 4, 3, 'leader', 'śr', 17);
SELECT dodanie_uczestinka(100, 4, 3, 'leader', 'śr', 17);
SELECT dodanie_uczestinka(53, 4, 3, 'leader', 'śr', 17);
SELECT dodanie_uczestinka(32, 4, 3, 'follower', 'śr', 17);
SELECT dodanie_uczestinka(100, 4, 3, 'leader', 'śr', 17);
SELECT dodanie_uczestinka(33, 4, 3, 'leader', 'śr', 17);
SELECT dodanie_uczestinka(45, 4, 3, 'leader', 'śr', 17);
SELECT dodanie_uczestinka(26, 4, 3, 'follower', 'śr', 17);
SELECT dodanie_uczestinka(52, 4, 3, 'follower', 'śr', 17);
SELECT dodanie_uczestinka(58, 4, 3, 'follower', 'śr', 17);
SELECT dodanie_uczestinka(35, 4, 3, 'follower', 'śr', 17);
SELECT dodanie_uczestinka(98, 4, 3, 'leader', 'śr', 17);
SELECT dodanie_uczestinka(67, 4, 3, 'leader', 'śr', 17);
SELECT dodanie_uczestinka(39, 4, 3, 'leader', 'śr', 17);
SELECT dodanie_uczestinka(35, 4, 3, 'leader', 'śr', 17);
INSERT INTO prowadzacy VALUES (4, 3, 10, 16);

SELECT dodanie_uczestinka(2, 5, 3, 'leader', 'śr', 19);
SELECT dodanie_uczestinka(90, 5, 3, 'follower', 'śr', 19);
SELECT dodanie_uczestinka(66, 5, 3, 'follower', 'śr', 19);
SELECT dodanie_uczestinka(87, 5, 3, 'leader', 'śr', 19);
SELECT dodanie_uczestinka(85, 5, 3, 'leader', 'śr', 19);
SELECT dodanie_uczestinka(83, 5, 3, 'follower', 'śr', 19);
SELECT dodanie_uczestinka(71, 5, 3, 'follower', 'śr', 19);
SELECT dodanie_uczestinka(30, 5, 3, 'follower', 'śr', 19);
SELECT dodanie_uczestinka(41, 5, 3, 'follower', 'śr', 19);
SELECT dodanie_uczestinka(59, 5, 3, 'leader', 'śr', 19);
SELECT dodanie_uczestinka(98, 5, 3, 'follower', 'śr', 19);
SELECT dodanie_uczestinka(5, 5, 3, 'leader', 'śr', 19);
SELECT dodanie_uczestinka(73, 5, 3, 'follower', 'śr', 19);
SELECT dodanie_uczestinka(11, 5, 3, 'leader', 'śr', 19);
SELECT dodanie_uczestinka(63, 5, 3, 'leader', 'śr', 19);
SELECT dodanie_uczestinka(42, 5, 3, 'leader', 'śr', 19);
SELECT dodanie_uczestinka(46, 5, 3, 'leader', 'śr', 19);
SELECT dodanie_uczestinka(95, 5, 3, 'leader', 'śr', 19);
SELECT dodanie_uczestinka(43, 5, 3, 'leader', 'śr', 19);
SELECT dodanie_uczestinka(29, 5, 3, 'leader', 'śr', 19);
SELECT dodanie_uczestinka(50, 5, 3, 'leader', 'śr', 19);
SELECT dodanie_uczestinka(99, 5, 3, 'follower', 'śr', 19);
SELECT dodanie_uczestinka(66, 5, 3, 'follower', 'śr', 19);
SELECT dodanie_uczestinka(99, 5, 3, 'follower', 'śr', 19);
SELECT dodanie_uczestinka(19, 5, 3, 'leader', 'śr', 19);
INSERT INTO prowadzacy VALUES (5, 3, 1, 9);

SELECT dodanie_uczestinka(4, 5, 5, 'leader', 'pt', 19);
SELECT dodanie_uczestinka(28, 5, 5, 'follower', 'pt', 19);
SELECT dodanie_uczestinka(52, 5, 5, 'follower', 'pt', 19);
SELECT dodanie_uczestinka(47, 5, 5, 'leader', 'pt', 19);
SELECT dodanie_uczestinka(46, 5, 5, 'leader', 'pt', 19);
SELECT dodanie_uczestinka(24, 5, 5, 'follower', 'pt', 19);
SELECT dodanie_uczestinka(14, 5, 5, 'follower', 'pt', 19);
SELECT dodanie_uczestinka(50, 5, 5, 'leader', 'pt', 19);
SELECT dodanie_uczestinka(59, 5, 5, 'follower', 'pt', 19);
SELECT dodanie_uczestinka(44, 5, 5, 'follower', 'pt', 19);
SELECT dodanie_uczestinka(47, 5, 5, 'leader', 'pt', 19);
SELECT dodanie_uczestinka(72, 5, 5, 'leader', 'pt', 19);
SELECT dodanie_uczestinka(90, 5, 5, 'leader', 'pt', 19);
SELECT dodanie_uczestinka(62, 5, 5, 'leader', 'pt', 19);
SELECT dodanie_uczestinka(49, 5, 5, 'leader', 'pt', 19);
SELECT dodanie_uczestinka(42, 5, 5, 'follower', 'pt', 19);
SELECT dodanie_uczestinka(38, 5, 5, 'leader', 'pt', 19);
SELECT dodanie_uczestinka(34, 5, 5, 'follower', 'pt', 19);
SELECT dodanie_uczestinka(69, 5, 5, 'leader', 'pt', 19);
SELECT dodanie_uczestinka(84, 5, 5, 'follower', 'pt', 19);
SELECT dodanie_uczestinka(22, 5, 5, 'follower', 'pt', 19);
SELECT dodanie_uczestinka(58, 5, 5, 'follower', 'pt', 19);
SELECT dodanie_uczestinka(53, 5, 5, 'follower', 'pt', 19);
SELECT dodanie_uczestinka(95, 5, 5, 'leader', 'pt', 19);
SELECT dodanie_uczestinka(16, 5, 5, 'leader', 'pt', 19);
INSERT INTO prowadzacy VALUES (5, 5, 5, 1);

SELECT dodanie_uczestinka(57, 4, 5, 'follower', 'pt', 17);
SELECT dodanie_uczestinka(2, 4, 5, 'leader', 'pt', 17);
SELECT dodanie_uczestinka(93, 4, 5, 'leader', 'pt', 17);
SELECT dodanie_uczestinka(100, 4, 5, 'leader', 'pt', 17);
SELECT dodanie_uczestinka(62, 4, 5, 'leader', 'pt', 17);
SELECT dodanie_uczestinka(70, 4, 5, 'follower', 'pt', 17);
SELECT dodanie_uczestinka(92, 4, 5, 'follower', 'pt', 17);
SELECT dodanie_uczestinka(12, 4, 5, 'leader', 'pt', 17);
SELECT dodanie_uczestinka(16, 4, 5, 'follower', 'pt', 17);
SELECT dodanie_uczestinka(11, 4, 5, 'follower', 'pt', 17);
SELECT dodanie_uczestinka(94, 4, 5, 'leader', 'pt', 17);
SELECT dodanie_uczestinka(80, 4, 5, 'follower', 'pt', 17);
SELECT dodanie_uczestinka(66, 4, 5, 'follower', 'pt', 17);
SELECT dodanie_uczestinka(57, 4, 5, 'follower', 'pt', 17);
SELECT dodanie_uczestinka(44, 4, 5, 'follower', 'pt', 17);
SELECT dodanie_uczestinka(48, 4, 5, 'leader', 'pt', 17);
SELECT dodanie_uczestinka(1, 4, 5, 'leader', 'pt', 17);
SELECT dodanie_uczestinka(62, 4, 5, 'follower', 'pt', 17);
SELECT dodanie_uczestinka(62, 4, 5, 'follower', 'pt', 17);
SELECT dodanie_uczestinka(20, 4, 5, 'leader', 'pt', 17);
SELECT dodanie_uczestinka(69, 4, 5, 'leader', 'pt', 17);
SELECT dodanie_uczestinka(76, 4, 5, 'follower', 'pt', 17);
SELECT dodanie_uczestinka(51, 4, 5, 'follower', 'pt', 17);
SELECT dodanie_uczestinka(2, 4, 5, 'follower', 'pt', 17);
SELECT dodanie_uczestinka(13, 4, 5, 'follower', 'pt', 17);
INSERT INTO prowadzacy VALUES (4, 5, 16, 10);

SELECT dodanie_uczestinka(17, 3, 5, 'follower', 'pt', 15);
SELECT dodanie_uczestinka(5, 3, 5, 'follower', 'pt', 15);
SELECT dodanie_uczestinka(66, 3, 5, 'follower', 'pt', 15);
SELECT dodanie_uczestinka(45, 3, 5, 'leader', 'pt', 15);
SELECT dodanie_uczestinka(29, 3, 5, 'follower', 'pt', 15);
SELECT dodanie_uczestinka(68, 3, 5, 'leader', 'pt', 15);
SELECT dodanie_uczestinka(94, 3, 5, 'leader', 'pt', 15);
SELECT dodanie_uczestinka(43, 3, 5, 'leader', 'pt', 15);
SELECT dodanie_uczestinka(85, 3, 5, 'follower', 'pt', 15);
SELECT dodanie_uczestinka(20, 3, 5, 'leader', 'pt', 15);
SELECT dodanie_uczestinka(70, 3, 5, 'leader', 'pt', 15);
SELECT dodanie_uczestinka(23, 3, 5, 'leader', 'pt', 15);
SELECT dodanie_uczestinka(46, 3, 5, 'follower', 'pt', 15);
SELECT dodanie_uczestinka(19, 3, 5, 'leader', 'pt', 15);
SELECT dodanie_uczestinka(10, 3, 5, 'follower', 'pt', 15);
SELECT dodanie_uczestinka(76, 3, 5, 'leader', 'pt', 15);
SELECT dodanie_uczestinka(92, 3, 5, 'leader', 'pt', 15);
SELECT dodanie_uczestinka(94, 3, 5, 'follower', 'pt', 15);
SELECT dodanie_uczestinka(93, 3, 5, 'leader', 'pt', 15);
SELECT dodanie_uczestinka(83, 3, 5, 'leader', 'pt', 15);
SELECT dodanie_uczestinka(24, 3, 5, 'follower', 'pt', 15);
SELECT dodanie_uczestinka(5, 3, 5, 'follower', 'pt', 15);
SELECT dodanie_uczestinka(15, 3, 5, 'leader', 'pt', 15);
SELECT dodanie_uczestinka(75, 3, 5, 'follower', 'pt', 15);
SELECT dodanie_uczestinka(56, 3, 5, 'follower', 'pt', 15);
INSERT INTO prowadzacy VALUES (3, 5, 8, 16);

SELECT dodanie_uczestinka(85, 3, 4, 'leader', 'czw', 15);
SELECT dodanie_uczestinka(18, 3, 4, 'follower', 'czw', 15);
SELECT dodanie_uczestinka(4, 3, 4, 'follower', 'czw', 15);
SELECT dodanie_uczestinka(98, 3, 4, 'follower', 'czw', 15);
SELECT dodanie_uczestinka(25, 3, 4, 'follower', 'czw', 15);
SELECT dodanie_uczestinka(43, 3, 4, 'leader', 'czw', 15);
SELECT dodanie_uczestinka(8, 3, 4, 'follower', 'czw', 15);
SELECT dodanie_uczestinka(30, 3, 4, 'leader', 'czw', 15);
SELECT dodanie_uczestinka(89, 3, 4, 'leader', 'czw', 15);
SELECT dodanie_uczestinka(3, 3, 4, 'leader', 'czw', 15);
SELECT dodanie_uczestinka(67, 3, 4, 'leader', 'czw', 15);
SELECT dodanie_uczestinka(48, 3, 4, 'follower', 'czw', 15);
SELECT dodanie_uczestinka(31, 3, 4, 'follower', 'czw', 15);
SELECT dodanie_uczestinka(75, 3, 4, 'follower', 'czw', 15);
SELECT dodanie_uczestinka(42, 3, 4, 'leader', 'czw', 15);
SELECT dodanie_uczestinka(98, 3, 4, 'follower', 'czw', 15);
SELECT dodanie_uczestinka(63, 3, 4, 'follower', 'czw', 15);
SELECT dodanie_uczestinka(84, 3, 4, 'leader', 'czw', 15);
SELECT dodanie_uczestinka(90, 3, 4, 'follower', 'czw', 15);
SELECT dodanie_uczestinka(37, 3, 4, 'follower', 'czw', 15);
SELECT dodanie_uczestinka(83, 3, 4, 'follower', 'czw', 15);
SELECT dodanie_uczestinka(11, 3, 4, 'follower', 'czw', 15);
SELECT dodanie_uczestinka(32, 3, 4, 'follower', 'czw', 15);
SELECT dodanie_uczestinka(9, 3, 4, 'follower', 'czw', 15);
SELECT dodanie_uczestinka(53, 3, 4, 'follower', 'czw', 15);
INSERT INTO prowadzacy VALUES (3, 4, 7, 10);

SELECT dodanie_uczestinka(53, 4, 4, 'leader', 'czw', 17);
SELECT dodanie_uczestinka(54, 4, 4, 'leader', 'czw', 17);
SELECT dodanie_uczestinka(42, 4, 4, 'leader', 'czw', 17);
SELECT dodanie_uczestinka(40, 4, 4, 'follower', 'czw', 17);
SELECT dodanie_uczestinka(17, 4, 4, 'leader', 'czw', 17);
SELECT dodanie_uczestinka(4, 4, 4, 'follower', 'czw', 17);
SELECT dodanie_uczestinka(32, 4, 4, 'leader', 'czw', 17);
SELECT dodanie_uczestinka(99, 4, 4, 'leader', 'czw', 17);
SELECT dodanie_uczestinka(3, 4, 4, 'leader', 'czw', 17);
SELECT dodanie_uczestinka(14, 4, 4, 'leader', 'czw', 17);
SELECT dodanie_uczestinka(26, 4, 4, 'follower', 'czw', 17);
SELECT dodanie_uczestinka(46, 4, 4, 'follower', 'czw', 17);
SELECT dodanie_uczestinka(45, 4, 4, 'follower', 'czw', 17);
SELECT dodanie_uczestinka(47, 4, 4, 'follower', 'czw', 17);
SELECT dodanie_uczestinka(70, 4, 4, 'leader', 'czw', 17);
SELECT dodanie_uczestinka(8, 4, 4, 'leader', 'czw', 17);
SELECT dodanie_uczestinka(94, 4, 4, 'leader', 'czw', 17);
SELECT dodanie_uczestinka(42, 4, 4, 'leader', 'czw', 17);
SELECT dodanie_uczestinka(80, 4, 4, 'follower', 'czw', 17);
SELECT dodanie_uczestinka(83, 4, 4, 'leader', 'czw', 17);
SELECT dodanie_uczestinka(14, 4, 4, 'leader', 'czw', 17);
SELECT dodanie_uczestinka(53, 4, 4, 'follower', 'czw', 17);
SELECT dodanie_uczestinka(15, 4, 4, 'leader', 'czw', 17);
SELECT dodanie_uczestinka(100, 4, 4, 'follower', 'czw', 17);
SELECT dodanie_uczestinka(40, 4, 4, 'follower', 'czw', 17);
INSERT INTO prowadzacy VALUES (4, 4, 12, 6);

SELECT dodanie_uczestinka(66, 5, 4, 'leader', 'czw', 19);
SELECT dodanie_uczestinka(97, 5, 4, 'leader', 'czw', 19);
SELECT dodanie_uczestinka(92, 5, 4, 'leader', 'czw', 19);
SELECT dodanie_uczestinka(47, 5, 4, 'follower', 'czw', 19);
SELECT dodanie_uczestinka(34, 5, 4, 'follower', 'czw', 19);
SELECT dodanie_uczestinka(8, 5, 4, 'leader', 'czw', 19);
SELECT dodanie_uczestinka(34, 5, 4, 'leader', 'czw', 19);
SELECT dodanie_uczestinka(32, 5, 4, 'follower', 'czw', 19);
SELECT dodanie_uczestinka(42, 5, 4, 'follower', 'czw', 19);
SELECT dodanie_uczestinka(11, 5, 4, 'leader', 'czw', 19);
SELECT dodanie_uczestinka(3, 5, 4, 'follower', 'czw', 19);
SELECT dodanie_uczestinka(88, 5, 4, 'leader', 'czw', 19);
SELECT dodanie_uczestinka(19, 5, 4, 'leader', 'czw', 19);
SELECT dodanie_uczestinka(35, 5, 4, 'follower', 'czw', 19);
SELECT dodanie_uczestinka(13, 5, 4, 'leader', 'czw', 19);
SELECT dodanie_uczestinka(20, 5, 4, 'follower', 'czw', 19);
SELECT dodanie_uczestinka(24, 5, 4, 'follower', 'czw', 19);
SELECT dodanie_uczestinka(60, 5, 4, 'leader', 'czw', 19);
SELECT dodanie_uczestinka(85, 5, 4, 'follower', 'czw', 19);
SELECT dodanie_uczestinka(64, 5, 4, 'leader', 'czw', 19);
SELECT dodanie_uczestinka(45, 5, 4, 'follower', 'czw', 19);
SELECT dodanie_uczestinka(48, 5, 4, 'leader', 'czw', 19);
SELECT dodanie_uczestinka(11, 5, 4, 'leader', 'czw', 19);
SELECT dodanie_uczestinka(94, 5, 4, 'leader', 'czw', 19);
SELECT dodanie_uczestinka(88, 5, 4, 'follower', 'czw', 19);
INSERT INTO prowadzacy VALUES (5, 4, 2, 13);

SELECT * FROM zajecia ORDER BY id_grupy, id_tanca;
